version: '3.8'

services:
  postgres:
    image: postgres:alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=wallet-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    volumes:
      - postgres-data:/var/lib/postgresql/data

  rabbitmq:
    container_name: rabbitmq
    depends_on:
      - postgres
    image: rabbitmq:management
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmq
      - RABBITMQ_DEFAULT_PASS=rabbitmq
  
  user-service:
    depends_on:
      - rabbitmq
    build: ./user-service
    ports:
      - 8080:8080
    environment:
      - RABBITMQ_HOST=rabbitmq
      - DB_URL=jdbc:postgresql://postgres:5432/wallet-db
    
  account-service:
    depends_on:
      - user-service
    build: ./account-service
    ports:
      - 8081:8081
    environment:
      - RABBITMQ_HOST=rabbitmq
      - DB_URL=jdbc:postgresql://postgres:5432/wallet-db
  
  operations-service:
    depends_on:
      - account-service
    build: ./operations-service
    ports:
      - 8082:8082
    environment:
      - RABBITMQ_HOST=rabbitmq
      - DB_URL=jdbc:postgresql://postgres:5432/wallet-db
    
  notification-service:
    depends_on:
      - operations-service
    build: ./notification-service
    ports:
      - 8083:8083
    environment:
      - RABBITMQ_HOST=rabbitmq

  payment-service:
    depends_on:
      - notification-service
    build: ./payment-service
    ports:
      - 8084:8084
    environment:
      - RABBITMQ_HOST=rabbitmq
  
  withdrawal-service:
    depends_on:
      - payment-service
    build: ./withdrawal-service
    ports:
      - 8085:8085
    environment:
      - RABBITMQ_HOST=rabbitmq

volumes:
  postgres-data:
